experiments/urls.py
from django.urls import path
from django.views.decorators.csrf import csrf_exempt

from accounts.views import (
    ConsentInfoView,
    DemographicInfoDeleteView,
    GroupManagerCheckView,
)

from .views import (
    EditableSettingsUpdateView,
    ExperimentCreateView,
    ExperimentDeleteView,
    ExperimentDetailView,
    ExperimentsPageView,
    ExperimentTasksPageView,
    ExperimentUpdateView,
    GroupManagerCreateView,
    GroupManagerMessageComposeView,
    GroupManagerMessageSendView,
    GroupManagerParticipantsExportView,
    GroupManagerParticipantsPageView,
    GroupManagersPageView,
    GroupManagerUpdateView,
    HomePageView,
    LogEntriesPageView,
    ParticipantsPageView,
    ParticipantTasksPageView,
    ParticipantTasksPaySumPageView,
    ParticipantUpdateView,
    TaskResetView,
    TasksCompleteView,
    TasksDeleteTestTaskView,
    TasksExportView,
    TasksFailView,
    TasksFinalizeView,
    TasksImportView,
    TasksPageView,
    TasksPayView,
    TasksStartView,
    TasksUpdateBonusView,
    TasksUpdateCommentView,
)

urlpatterns = [
    path(
        "experiments/group_managers/create",
        GroupManagerCreateView.as_view(),
        name="experiments-group_managers-create",
    ),
    path(
        "experiments/group_managers/update/<int:pk>",
        GroupManagerUpdateView.as_view(),
        name="experiments-group_managers-update",
    ),
    path(
        "experiments/group_managers/<int:pk>/participants",
        GroupManagerParticipantsPageView.as_view(),
        name="experiments-group_manager-participants",
    ),
    path(
        "experiments/group_managers/<int:pk>/participants/export",
        GroupManagerParticipantsExportView.as_view(),
        name="group-manager_participants_export",
    ),
    path(
        "group_managers/<int:pk>/compose_message",
        GroupManagerMessageComposeView.as_view(),
        name="experiments-group_manager-compose_message",
    ),
    path(
        "group_managers/send_message",
        GroupManagerMessageSendView.as_view(),
        name="experiments-group_manager-send_message",
    ),
    path(
        "experiments/experiments/create",
        ExperimentCreateView.as_view(),
        name="experiments-experiments-create",
    ),
    path(
        "experiments/experiments/update/<int:pk>",
        ExperimentUpdateView.as_view(),
        name="experiments-experiments-update",
    ),
    path(
        "experiments/group_managers",
        GroupManagersPageView.as_view(),
        name="experiments-group_managers",
    ),
    path("experiments/tasks", TasksPageView.as_view(), name="experiments-tasks"),
    path(
        "experiments/participants",
        ParticipantsPageView.as_view(),
        name="experiments-participants",
    ),
    path(
        "experiments/participants/<int:pk>/update",
        ParticipantUpdateView.as_view(),
        name="experiments-participants-update",
    ),
    path(
        "accounts/<int:pk>/delete",
        DemographicInfoDeleteView.as_view(),
        name="accounts-delete",
    ),
    path(
        "experiments/experiments",
        ExperimentsPageView.as_view(),
        name="experiments-experiments",
    ),
    path(
        "experiments/<int:pk>/delete",
        ExperimentDeleteView.as_view(),
        name="experiments-delete",
    ),
    path(
        "experiments/experiment/<int:pk>",
        ExperimentDetailView.as_view(),
        name="experiment-detail",
    ),
    path(
        "experiments/<int:pk>/tasks",
        ExperimentTasksPageView.as_view(),
        name="experiments-experiment-tasks",
    ),
    path(
        "experiments/participants/<int:pk>/tasks",
        ParticipantTasksPageView.as_view(),
        name="experiments-participant-tasks",
    ),
    path(
        "hits/complete",
        csrf_exempt(TasksCompleteView.as_view()),
        name="tasks-complete",
    ),
    path(
        "tasks/complete",
        csrf_exempt(TasksCompleteView.as_view()),
        name="tasks-complete",
    ),
    path(
        "hits/fail",
        csrf_exempt(TasksFailView.as_view()),
        name="tasks-fail",
    ),
    path(
        "tasks/fail",
        csrf_exempt(TasksFailView.as_view()),
        name="tasks-fail",
    ),
    path(
        "tasks/finalize/<int:pk>",
        TasksFinalizeView.as_view(),
        name="tasks-finalize",
    ),
    path(
        "tasks/<int:pk>/delete",
        TaskResetView.as_view(),
        name="tasks-delete",
    ),
    path(
        "tasks/delete_test_task",
        TasksDeleteTestTaskView.as_view(),
        name="tasks-delete-test-task",
    ),
    path(
        "tasks/pay/<int:pk>",
        TasksPayView.as_view(),
        name="tasks-pay",
    ),
    path(
        "tasks/<int:pk>/update_bonus",
        csrf_exempt(TasksUpdateBonusView.as_view()),
        name="tasks-bonus-update",
    ),
    path(
        "experiments/participants/<int:pk>/tasks/pay_sum",
        ParticipantTasksPaySumPageView.as_view(),
        name="participant-tasks-pay-sum",
    ),
    path(
        "tasks/start",
        csrf_exempt(TasksStartView.as_view()),
        name="tasks-start",
    ),
    path(
        "tasks/<int:pk>/update_comment",
        csrf_exempt(TasksUpdateCommentView.as_view()),
        name="tasks-update-comment",
    ),
    path("", HomePageView.as_view(), name="home"),
    path(
        "experiments/<int:pk>/tasks/export",
        TasksExportView.as_view(),
        name="tasks_export",
    ),
    path("tasks/import", TasksImportView.as_view(), name="tasks_import"),
    path(
        "experiments/editable_settings/<int:pk>/update",
        EditableSettingsUpdateView.as_view(),
        name="experiments-editable_settings-update",
    ),
    path("consent_info", ConsentInfoView.as_view(), name="consent-info"),
    path(
        "group_manager/check",
        GroupManagerCheckView.as_view(),
        name="group_manager-check",
    ),
    path(
        "experiments/log_entries",
        LogEntriesPageView.as_view(),
        name="experiments-log_entries",
    ),
]

experiments/models.py
import asyncio
import logging
import time
from datetime import date, timedelta

import aiohttp
from aiohttp import ClientConnectorError
from aiohttp.client import ClientSession
from auditlog.registry import auditlog
from django.db import models
from django.db.models import Sum
from django.urls import reverse
from django.utils import timezone
from django_fsm import FSMField, transition
from django_request_cache import cache_for_request

from .utils import get_scheme_and_netloc

logger = logging.getLogger(__name__)


class Experiment(models.Model):
    title = models.CharField(max_length=255, db_index=True, null=False, blank=False)
    description = models.TextField(null=False, blank=True)
    url = models.CharField(max_length=2048, db_index=True, null=False, blank=True)
    username = models.CharField(max_length=64, null=True, blank=True)
    password = models.CharField(max_length=32, null=True, blank=True)
    use_for_test_tasks = models.BooleanField(default=False, blank=True)
    batches = models.IntegerField(null=False, default=1)
    estimated_duration = models.IntegerField(null=False, blank=False, default=0)
    max_duration = models.IntegerField(null=True, blank=True)
    notes = models.TextField(null=False, blank=True, default="")

    # foreign keys
    create_user = models.ForeignKey(
        "accounts.CustomUser",
        blank=True,
        null=True,
        on_delete=models.SET_NULL,
        related_name="cap_recruiter_experiment_create_user_id",
    )
    update_user = models.ForeignKey(
        "accounts.CustomUser",
        null=True,
        on_delete=models.SET_NULL,
        related_name="cap_recruiter_experiment_update_user_id",
    )

    # timestamps
    start_date = models.DateField()
    expire_date = models.DateField()
    created_at = models.DateTimeField(db_index=True, auto_now_add=True)
    updated_at = models.DateTimeField(db_index=True, auto_now=True)
    deleted_at = models.DateTimeField(db_index=True, null=True)

    def sorted_group_managers(self):
        unsorted_group_managers = [
            group_manager for group_manager in self.group_managers.all()
        ]
        return sorted(
            unsorted_group_managers, key=lambda group_manager: group_manager.full_name()
        )

    def days_until_expiry(self):
        return (self.expire_date - date.today()).days

    def days_until_start(self):
        return (self.start_date - date.today()).days

    def get_absolute_url(self):
        return reverse("experiments-experiments")

    def tasks_count(self):
        return self.tasks.count()

    def worker_name(self):
        return self.worker.full_name()

    def base_payment_sum(self):
        return self.tasks.aggregate(Sum("base_payment"))["base_payment__sum"]

    def bonus_sum(self):
        return self.tasks.aggregate(Sum("bonus"))["bonus__sum"]

    def total_base_payments(self):
        tasks = self.tasks

        if not tasks:
            return 0
        return tasks.aggregate(Sum("base_payment")).get("base_payment__sum")

    def total_bonuses(self):
        tasks = self.tasks

        if not tasks:
            return 0
        return tasks.aggregate(Sum("bonus")).get("bonus__sum")

    def total_payments(self):
        tasks = self.tasks

        if not tasks:
            return 0

        base_payment_sum = tasks.aggregate(Sum("base_payment")).get("base_payment__sum")
        if base_payment_sum is None:
            return 0

        bonus_sum = tasks.aggregate(Sum("bonus")).get("bonus__sum")

        return bonus_sum + base_payment_sum

    def total_sum(self):
        if None in [self.base_payment_sum(), self.bonus_sum()]:
            return 0
        return self.base_payment_sum() + self.bonus_sum()

    def has_expired(self):
        return self.expire_date < date.today()

    def is_deleted(self):
        return self.deleted_at is not None

    def is_active(self):
        if (
            self.is_deleted()
            or self.has_expired()
            or (not self.has_group_managers_assigned() and not self.use_for_test_tasks)
        ):
            return False
        return True

    def is_active_and_deployed(self):
        return self.is_active() and self.id in Experiment.deployed_experiments()

    def has_group_managers_assigned(self):
        if len(self.group_managers.all()) > 0:
            return True
        return False

    def dashboard_url(self):
        return f"{get_scheme_and_netloc(self.url)}/dashboard"

    def test_tasks_experiment(self):
        return self.objects.filter(self.initial_test_experiment_id).first()

    @classmethod
    @cache_for_request
    def deployed_experiments(cls):
        async def get_deployed_experiment_id(url: dict, session: ClientSession):
            try:
                async with session.get(url["url"]) as response:
                    if response.status == 200:
                        return url["id"]
            except ClientConnectorError:
                return None

        async def get_deployed_experiment_ids(urls: list):
            my_conn = aiohttp.TCPConnector(limit=10)
            async with aiohttp.ClientSession(connector=my_conn) as session:
                tasks = []
                for url in urls:
                    task = asyncio.ensure_future(
                        get_deployed_experiment_id(url=url, session=session)
                    )
                    tasks.append(task)
                responses = await asyncio.gather(*tasks, return_exceptions=True)
            return responses

        url_list = [
            {"id": experiment.id, "url": get_scheme_and_netloc(experiment.url)}
            for experiment in cls.objects.exclude(deleted_at__isnull=False).order_by(
                "-created_at"
            )
        ]
        start = time.time()
        experiment_ids = [
            _id
            for _id in asyncio.run(get_deployed_experiment_ids(url_list))
            if _id is not None
        ]
        end = time.time()
        logger.info(
            f"Deployed experiment ids {experiment_ids} for {len(url_list)} URLs returned in {end - start} seconds."
        )

        return experiment_ids

    @classmethod
    def exists_deployed_experiment(cls):
        if not cls.deployed_experiments():
            return False
        return True


class Payment(models.Model):
    state = models.CharField(max_length=20, db_index=True, null=False)

    STATES = (
        ("paid", "Paid"),
        ("received", "Received"),
        ("unpaid", "Unpaid"),
    )
    state = FSMField(default="unpaid", protected=True, choices=STATES)

    task = models.OneToOneField(
        "Task",
        null=False,
        on_delete=models.CASCADE,
        primary_key=True,
        related_name="payment",
    )

    worker = models.ForeignKey(
        "accounts.CustomUser",
        null=False,
        on_delete=models.CASCADE,
        related_name="payments",
    )

    amount = models.FloatField(default=0)

    # timestamps
    paid_at = models.DateTimeField(db_index=True, null=True)
    received_at = models.DateTimeField(db_index=True, null=True)

    # state transitions
    @transition(field=state, source="unpaid", target="paid")
    def pay(self):
        pass

    @transition(field=state, source="paid", target="received")
    def receive(self):
        pass


class Task(models.Model):
    state = models.CharField(max_length=20, db_index=True, null=False)
    assignment_id = models.CharField(max_length=200, db_index=True, null=False)

    # foreign keys
    experiment = models.ForeignKey(
        Experiment,
        null=False,
        on_delete=models.CASCADE,
        related_name="tasks",
    )
    group_manager = models.ForeignKey(
        "accounts.GroupManager",
        null=False,
        on_delete=models.CASCADE,
        related_name="tasks",
    )
    worker = models.ForeignKey(
        "accounts.CustomUser",
        null=False,
        on_delete=models.CASCADE,
        related_name="tasks",
    )

    STATES = (
        ("started", "Started"),
        ("completed", "Completed"),
        ("not_completed", "Not completed"),
        ("payment_done", "Payment done"),
        ("payment_received", "Payment received"),
        ("reset", "Reset"),
    )
    state = FSMField(default="started", protected=True, choices=STATES)

    # state transitions
    @transition(field=state, source=["started", "not_completed"], target="completed")
    def complete(self):
        pass

    @transition(field=state, source="started", target="not_completed")
    def fail(self):
        pass

    @transition(
        field=state, source=["completed", "not_completed"], target="payment_done"
    )
    def pay(self):
        pass

    @transition(field=state, source="payment_done", target="payment_received")
    def finalize(self):
        pass

    @transition(field=state, source="not_completed", target="reset")
    def reset(self):
        pass

    base_payment = models.FloatField(default=0)
    bonus = models.FloatField(default=0)
    comment = models.TextField(blank=True, default="")
    batch = models.IntegerField(null=False, default=1)
    failed_reason = models.TextField(blank=True, default="")

    # timestamps
    reset_at = models.DateTimeField(db_index=True, null=True)
    started_at = models.DateTimeField(db_index=True, auto_now_add=True)
    completed_at = models.DateTimeField(db_index=True, null=True)
    failed_at = models.DateTimeField(db_index=True, null=True)
    deleted_at = models.DateTimeField(db_index=True, null=True)
    payment_done_at = models.DateTimeField(db_index=True, null=True)
    payment_received_at = models.DateTimeField(db_index=True, null=True)

    class Meta:
        constraints = [
            models.UniqueConstraint(
                fields=["worker", "experiment", "batch", "reset_at"],
                name="unique_worker_experiment_batch_reset_at",
            ),
        ]

    def is_test_task(self):
        return self.experiment.use_for_test_tasks

experiments/templates/superuser/experiment_detail.html
{% extends 'base.html' %}

{% load tags %}
{% load bootstrap4 %}

{% block content %}
  {% include "header.html" %}
  {% if user.is_authenticated %}
    {% if user.is_superuser %}
      <div class="justify-content-center" style="display: flex; margin-top: 50px;">
        <div class="col-md-6">
          <div class="card">
            <div class="card-header">
              <h5 style="margin-bottom: 0px; float: left;"><b>{{experiment.title}}</b></h5>
              {% if experiment.id in deployed_experiments %}
                <span style="float: right; background-color: lightgreen; margin-left:4px; padding: 2px 7px; font-weight: bold;">Deployed</span>
              {% endif %}
              {% if experiment.is_active %}
                <span style="float: right; background-color: gold; margin-left: 4px; padding: 2px 7px; font-weight: bold;">Active</span>
                </span>
              {% endif %}
              {% if experiment.use_for_test_tasks %}
                <span id="test-tasks" class="colored-box initial-test" style="font-weight: bold; float: right; padding: 2px 7px;">Initial test</span>
              {% endif %}
            </div>
            <div class="card-body">
              <form>
                <div class="form-group">
                  <label for="id_title">Title</label>
                  <input type="text" name="title" value="{{experiment.title}}" class="form-control" id="id_title" disabled>
                </div>
                <div class="form-group">
                  <label for="id_description">Description</label>
                  <input type="text" name="description" value="{{experiment.description}}" class="form-control" id="id_description" disabled>
                </div>
                <div class="form-group">
                  <label for="id_start_date">Start date</label>
                  <input type="text" name="start_date_month" value="{{experiment.start_date}}" class="form-control" id="id_start_date_month" disabled>
                </div>
                <div class="form-group">
                  <label for="id_expire_date">Expire date</label>
                  <input type="text" name="expire_date" value="{{experiment.expire_date}}" class="form-control" id="id_expire_date" disabled>
                </div>
                <div class="form-group">
                  <label for="id_estimated_duration">Estimated duration (in minutes)</label>
                  <input type="number" name="estimated_duration" value="{{experiment.estimated_duration}}" class="form-control" id="id_estimated_duration" disabled>
                </div>
                <div class="form-group">
                  <label for="id_max_duration">Maximum duration (in minutes)</label>
                  <input type="number" name="max_duration" value="{{experiment.max_duration}}" class="form-control" id="id_max_duration" disabled>
                </div>
                <div class="form-group">
                  <label for="id_batches">Batches</label>
                  <input type="number" name="batches" value="{{experiment.batches}}" class="form-control" id="id_batches" disabled>
                </div>
                <div class="form-group">
                  <div class="form-check">
                    <input type="checkbox" name="use_for_test_tasks" class="form-check-input" id="id_use_for_test_tasks" {% if experiment.use_for_test_tasks %}checked=""{% endif %}>
                    <label class="form-check-label" for="id_use_for_test_tasks">Initial test experiment</label>
                  </div>
                </div>
                <div class="form-group">
                  <label for="id_url">URL</label>
                  <input type="text" name="url" value="{{experiment.url}}" class="form-control" id="id_url" disabled>
                </div>
                <div class="form-group">
                  <label for="id_dashboard_url">Dashboard URL</label>
                  <input type="text" name="dashboard_url" value="{{experiment.dashboard_url}}" style="width: 95%; margin-bottom: 15px;" class="form-control" disabled="" id="id_dashboard_url">
                  <span id="open-dashboard-url"></span>
                </div>
                <div class="form-group">
                  <label for="id_username">Username</label>
                  <input type="text" name="username" value="{{experiment.username}}" style="width: 95%; margin-bottom: 15px;" class="form-control" id="id_username" disabled>
                  <span id="copy-username"></span>
                </div>
                <div class="form-group">
                  <label for="id_password">Password</label>
                  <input type="password" name="password" value="{{experiment.password}}" style="width: 95%; margin-bottom: 15px;" class="form-control" id="id_password" disabled>
                  <span id="copy-password"></span>
                </div>
                <div class="form-group">
                  <label for="id_notes">Notes</label>
                  <textarea name="notes" cols="40" rows="10" class="form-control" id="id_notes" disabled>{{experiment.notes}}</textarea></div>
                <div class="form-group">
                  <label for="id_description">Groups</label>
                  <select name="group_managers" class="form-control" id="id_group_managers" multiple="" disabled>
                    {% for group_manager in experiment.group_managers.all %}
                      <option value="{{group_manager.id}}" style="cursor: pointer;">{{group_manager.full_name}} ({{group_manager.code}})</option>
                    {% endfor %}
                  </select>
                </div>
              </form>
            </div>
          </div>
        </div>
      </div>

      <span class="frontend-module" data-name="superuser/notifications"></span>

      <script>
        wsProtocol = '{{ws_protocol}}';
        wsHost = '{{ws_host}}';
        customUserId = {{custom_user_id}};

        {% if experiment.id in deployed_experiments %}
        $("#id_dashboard_url").after(function() {
          return '<a href="{{experiment.dashboard_url}}" style="color: black;" target="_blank"><span id="open-dashboard-url"><i class="fa fa-lg fa-link" style="float: right; cursor: pointer; color: black; margin-top: -45px;" title="Open experiment dashboard"></i></a>';
        });
        {% endif %}

        $("#id_username").after(function() {
          return '<span id="copy-username"><i class="fa fa-lg fa-copy" style="float: right; cursor: pointer; color: #007bff; margin-top: -45px;"'
          + ' title="Copy username"></i></span>';
        });

        $("#id_password").after(function() {
          return '<span id="copy-password"><i class="fa fa-lg fa-copy" style="float: right; cursor: pointer; color: #007bff; margin-top: -45px;"'
          + ' title="Copy password"></i></span>';
        });

        document.getElementById("copy-username").onclick = function() {
          let element = document.createElement('textarea');
          element.value = $('#id_username').val();
          document.body.appendChild(element);
          element.select();
          document.execCommand('copy');
          document.body.removeChild(element);
        };

        document.getElementById("copy-password").onclick = function() {
          let element = document.createElement('textarea');
          element.value = $('#id_password').val();
          document.body.appendChild(element);
          element.select();
          document.execCommand('copy');
          document.body.removeChild(element);
        };
      </script>
    {% endif %}
  {% else %}
    {% include "not_logged_in.html" %}
  {% endif %}
{% endblock content %}

experiments/templates/superuser/group_manager_participants.html
{% load tags %}

{% include "header.html" %}
<div class="card-header" style="height: 60px;">
  <div style="float: left; padding-top: 8px;">
    <h5>
      <b>{{participants|length}} Participant{{participants|length|pluralize:"s"}} ({{group_manager.group_manager_name}} - {{group_manager.full_name}})</b>
    </h5>
  </div>
  <div class="btn-toolbar mb-2 mb-md-0" style="float: right;">
    <div class="btn-group mr-2">
      <button style="float: right; margin-left: 8px;" id="export-participants" class="btn btn-secondary" style="margin-left: 8px;" data-group-manager-id="{{group_manager.id}}">Export participants</button>
    </div>
  </div>
</div>
<div class="card-body">
  <table class="styled-table {{user_type}}">
    <thead>
      <tr style="font-weight: bold;">
        <td>First name<br>{% include "sort.html" with sort_by='first_name' %}</td>
        <td>Last name<br>{% include "sort.html" with sort_by='last_name' %}</td>
        <td style="text-align: center;">Recruitment ID<br>{% include "sort.html" with sort_by='worker_id' %}</td>
        <td style="text-align: center;">Tasks<br>{% include "sort.html" with sort_by='worker_tasks_count' %}</td>
        <td style="text-align: center;">Outstanding<br>payments{% include "sort.html" with sort_by='outstanding_payments_sum' %}</td>
        <td style="text-align: center;">Email<br>{% include "sort.html" with sort_by='email' %}</td>
        <td>Country<br>{% include "sort.html" with sort_by='country_name' %}</td>
        <td style="text-align: center;">
          Birthday (Age)<br>{% include "sort.html" with sort_by='age' %}
        </td>
        <td style="text-align: center;">Gender<br>{% include "sort.html" with sort_by='gender' %}</td>
        <td style="text-align: center;">Years of musical<br>experience{% include "sort.html" with sort_by='years_of_experience' %}</td>
        <td style="text-align: center;">Date joined<br>{% include "sort.html" with sort_by='date_joined' %}</td>
        <td style="text-align: center;">Verified<br>{% include "sort.html" with sort_by='is_verified' %}</td>
        <td style="text-align: center;">Initial test<br>{% include "sort.html" with sort_by='test_task_verified' %}</td>
        <td style="text-align: center;">Nonresponsive<br>{% include "sort.html" with sort_by='nonresponsive' %}</td>
        <td style="vertical-align: bottom;">
          <div id="toggle_include-deleted" style="float: right;">
            <input type="checkbox" id="include-deleted" style="cursor: pointer;">
            <label for="include-deleted" style="white-space: nowrap; margin: 0; cursor: pointer;">
              Include deleted
            </label>
          </div>
        </td>
      </tr>
    </thead>
    {% for participant in participants %}
      <tr>
      <td>
        {% if participant.has_failed_tasks %}
          <i class="fa fa-exclamation" style="color:red; font-weight: bold; margin-right: 7px; cursor: pointer;" title="Participant has failed tasks"></i>
        {% endif %}
        {{participant.first_name}}
      </td>
      <td>{{participant.last_name}}</td>
      <td><span style="font-family: monospace, monospace;">{{participant.worker_id}}</span></td>
      <td style="text-align: center;">
        {% if participant.worker_tasks_count > 0 %}
        <a href="{% url 'experiments-participant-tasks' participant.id %}" class="count">{{participant.worker_tasks_count}}</a>
        {% endif %}
      </td>
      <td style="text-align: center;" class="{% if participant.has_finished_non_test_task %}outstanding_payment{% else %}test_task_payment{% endif %}">
        {% if participant.outstanding_payments_sum > 0 %}
        {{participant.outstanding_payments_sum|as_dollars}}
        {% endif %}
      </td>
      <td style="text-align: center;">{{participant.email}}</td>
      <td>{{participant.country_name}}</td>
      <td style="text-align: center;">
        {% if participant.date_of_birth %}
          {{participant.date_of_birth}} ({{participant.age}})
        {% endif %}
      </td>
      <td style="text-align: center;">{{participant.gender}}</td>
      <td style="text-align: center;">{{participant.years_of_experience|floatformat}}</td>
      <td style="text-align: center;">{{participant.date_joined}}</td>
      <td style="text-align: center;">
        {% if participant.is_verified %}
          <span title="Verified" style="cursor: default; font-size: large; font-weight: bold;">✓</span>
        {% endif %}
      </td>
      <td style="text-align: center;">
        {% if participant.test_task_verified %}
          <span title="Initial test verified" style="cursor: default; font-size: large; font-weight: bold;">✓</span>
        {% endif %}
      </td>
      <td style="text-align: center;">
        <input type="checkbox" id="nonresponsive" name="nonresponsive" {% if participant.nonresponsive %}checked=""{% endif %} style=" accent-color: #ff0202;" readonly onclick="return false;">
      </td>
      <td style="min-width: 160px;">
        {% if not participant.is_deleted %}
        <button type="button" class="btn btn-sm btn-primary" onclick="location.href='/experiments/participants/{{participant.id}}/update'">Edit</button>
        <button type="button" class="btn btn-sm btn-danger btn-delete" data-toggle="modal" data-participant-id="{{participant.id}}" data-target="#confirm-account-deletion">Delete</button>
        {% endif %}
      </td>
    </tr>
    {% endfor %}
  </table>
</div>

<div class="modal fade" id="confirm-account-deletion" tabindex="-1" role="dialog" aria-labelledby="modalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-body">
        By clicking the <i>DELETE ACCOUNT</i> button all account data of this user will be permanently erased!
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
        <a id="btn-delete-modal" class="btn btn-danger" data-participant-id="">DELETE ACCOUNT</a>
      </div>
    </div>
  </div>
</div>

<span class="frontend-module" data-name="superuser/group-manager_participants"></span>
<span class="frontend-module" data-name="superuser/notifications"></span>

<script>
  wsProtocol = '{{ws_protocol}}';
  wsHost = '{{ws_host}}';
  customUserId = {{custom_user_id}};
  groupManagerId = {{group_manager.id}};
</script>

experiments/templates/superuser/import_csv_form.html
<div class="input-group">
  <div class="custom-file">
    <form action="/experiments/tasks/import" method="post" enctype="multipart/form-data" name="importForm">
      {% csrf_token %}
      <input type="file" name="csv_file" class="custom-file-input" id="csv_import_file" style="width: 400px; cursor: pointer;">
      <input type="hidden" name="experiment_id" value="{{experiment.id}}">
      <label class="custom-file-label" for="csv_import_file" style="white-space: nowrap; overflow: hidden;">Choose Task data file to import</label>
    </form>
  </div>
  <div class="input-group-append">
    <span class="input-group-text" id="csv_import_file_button" style="cursor: default; color: #fff; background-color: #007bff; border-color: #007bff;">Update Tasks</span>
  </div>
</div>

<span class="frontend-module" data-name="superuser/import_csv"></span>